name: PlatformIO CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build firmware
        run: pio run

      - name: Build LittleFS filesystem
        run: pio run -t buildfs

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: esp32-build
          path: |
            .pio/build/*/firmware.bin
            .pio/build/*/littlefs.bin
